[package]
name = "nd"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
atty = "0.2"
clap = { version = "3.2", features = ["derive"] }
memchr = "2.5"
rand = { version = "0.8", features = ["small_rng"] }
regex = "1.6"
num-runtime-fmt = "0.1"
tempfile = "3.3"
